examples = {
    "politics": "En un movimiento sorprendente, los principales partidos políticos en España anunciaron hoy la formación de un nuevo pacto de coalición que desafía las fronteras tradicionales del espectro político. El acuerdo histórico, forjado entre el Partido Socialista Obrero Español (PSOE), el Partido Popular (PP), Ciudadanos (Cs) y Unidas Podemos, ha enviado ondas de sorpresa a través del panorama político español.",
    "fashion": "La pasarela madrileña se convirtió en un crisol de creatividad y expresión durante el destacado desfile de moda que tuvo lugar en el corazón de la capital española. Bajo el lema 'Diversidad en la Pasarela', diseñadores de renombre y talentos emergentes se unieron para celebrar la inclusión en la industria de la moda.",
    "economy": "La economía se divide en varias ramas, como la microeconomía y la macroeconomía. La microeconomía se enfoca en el comportamiento de agentes económicos individuales, como consumidores y empresas, así como en la interacción entre ellos en mercados específicos. Mientras tanto, la macroeconomía analiza la economía en su conjunto, centrándose en variables como el producto interno bruto (PIB), el desempleo, la inflación y las políticas fiscales y monetarias.",
    "medicine": "La medicina moderna también se centra en la prevención de enfermedades, mediante la promoción de hábitos saludables, la vacunación, el control de factores de riesgo y la detección temprana de condiciones médicas potencialmente graves. La investigación médica juega un papel crucial en el avance de nuestros conocimientos sobre enfermedades y tratamientos, permitiendo el desarrollo de nuevas terapias y la mejora de las existentes.",
    "military": "Los drones equipados con sensores de alta precisión y cámaras de alta resolución están siendo desplegados para realizar operaciones de reconocimiento y vigilancia en zonas de difícil acceso, proporcionando a las fuerzas armadas una ventaja táctica y una mayor conciencia situacional.",
    "sports": "La final, disputada contra uno de los equipos más poderosos del mundo del baloncesto, fue un enfrentamiento épico que mantuvo la intensidad hasta el último segundo. Con jugadas magistrales, defensa impenetrable y un juego en equipo impecable, España emergió victoriosa, asegurando su lugar en la historia del deporte y llevando la emoción a millones de seguidores en todo el país.",
    "tech": "Desde sus primeras versiones, como Windows 1.0 y Windows 3.1, hasta las iteraciones más recientes como Windows 10 y Windows 11, el sistema operativo ha experimentado una serie de transformaciones significativas en términos de funcionalidad, interfaz de usuario y seguridad.",
    "religion": "La religión ha sido una parte fundamental de la historia humana, moldeando culturas, sociedades y mentalidades a lo largo de milenios. El Islam, una de las religiones más influyentes del mundo, se basa en el Corán y las enseñanzas de Mahoma, promoviendo la sumisión a Alá y la práctica de los cinco pilares: la profesión de fe, la oración, el ayuno, la limosna y la peregrinación a La Meca. ",
    "motor": "Los motores, ya sean de coches o motos, son el corazón de la pasión automovilística. Su rugido evoca emociones indescriptibles, mientras que su potencia impulsa la adrenalina a límites insospechados. Desde los clásicos motores de combustión interna hasta las innovadoras tecnologías eléctricas, cada avance redefine los estándares de rendimiento y eficiencia. Los coches deportivos deslumbran con su elegancia aerodinámica y su elevada potencia para alcanzar altas velocidades. Las motos en cambio, tienen una mayor aceleración debido a sus pocos kilos, y relación peso potencia.",
    "play": "El ocio contemporáneo ha sido redefinido por la explosión de opciones digitales, desde videojuegos envolventes hasta catálogos infinitos de películas y series. Los videojuegos ofrecen mundos interactivos donde la imaginación se fusiona con la tecnología, atrayendo a millones de jugadores ávidos de desafíos y narrativas emocionantes. Por otro lado, el universo cinematográfico y televisivo ofrece una variedad infinita de historias que abarcan géneros y culturas, desde épicas galácticas hasta dramas íntimos.",
    "alimentation": "Entre los platos más emblemáticos de la cocina madrileña se encuentra el cocido madrileño, un guiso tradicional compuesto por garbanzos, carne de cerdo, ternera, pollo, chorizo y verduras, que se sirve en tres vuelcos: sopa, garbanzos con verduras y finalmente la carne. Este plato es un símbolo de la cocina casera y reconfortante de Madrid, especialmente popular durante los meses más fríos del año.",
    "astronomy": "La astronomía, fascinante ciencia que estudia los astros y el universo, nos transporta a mundos lejanos y misterios cósmicos. Desde la Tierra, observamos estrellas titilantes, planetas errantes y galaxias distantes, cada uno con su propia historia y belleza única. Los planetas, como Venus con su resplandeciente atmósfera o Júpiter con sus gigantescas tormentas, despiertan nuestra curiosidad y asombro. "
}